### ISSUE TITLE
Wrong import of e from scipy?

### ISSUE THREAD

**Issue by zeyuan-ni** [kumagai-group/pydefect_2d#1]
Hello Kumagai-sensei,

This is Zeyuan Ni.
I got the error message below when trying to run pydefect_2d:
```bash
pydefect_2d --help
   INFO: -- Settings from vise.yaml:
   INFO: 
   INFO: -- Settings from pydefect.yaml:
   INFO: 
Traceback (most recent call last):
  File "/home/t180234/packages_dev/vasp_workflows/.venv/bin/pydefect_2d", line 5, in <module>
    from pydefect_2d.cli.main import main
  File "/home/t180234/packages_dev/vasp_workflows/.venv/lib/python3.9/site-packages/pydefect_2d/cli/main.py", line 13, in <module>
    from pydefect_2d.cli.main_function import make_gauss_diele_dist, \
  File "/home/t180234/packages_dev/vasp_workflows/.venv/lib/python3.9/site-packages/pydefect_2d/cli/main_function.py", line 20, in <module>
    from pydefect_2d.correction.gauss_energy import make_gauss_energies
  File "/home/t180234/packages_dev/vasp_workflows/.venv/lib/python3.9/site-packages/pydefect_2d/correction/gauss_energy.py", line 18, in <module>
    from pydefect_2d.correction.isolated_gauss import IsolatedGaussEnergy
  File "/home/t180234/packages_dev/vasp_workflows/.venv/lib/python3.9/site-packages/pydefect_2d/correction/isolated_gauss.py", line 13, in <module>
    from scipy import integrate, e
ImportError: cannot import name 'e' from 'scipy'
```
Maybe the import should be done like
`from scipy.constants import e`
See https://docs.scipy.org/doc/scipy/reference/constants.html

**Comment by zeyuan-ni** [comment]
```
pip freeze|grep pydefect:
pydefect==0.9.4
pydefect-2d==0.1.0

pip freeze|grep scipy
scipy==1.13.1
```

**Comment by yuuukuma** [comment]
Thank you for your suggestion. After fixing and refactoring the other part, I will update the pip version.
